### ISSUE TITLE
Failed running Openpiv_Python_Cython_GPU_demo.ipynb

### ISSUE THREAD

**Issue by ruinianxu** [OpenPIV/openpiv-python-gpu#22]
**Describe the bug**
Run [Openpiv_Python_Cython_GPU_demo.ipynb](https://github.com/OpenPIV/openpiv-python-gpu/blob/master/Openpiv_Python_Cython_GPU_demo.ipynb) will throw me the following error
```
AttributeError: module 'openpiv.gpu_process' has no attribute 'WiDIM'
```
I just wonder if this notebook is out-of-date.

**Comment by alexlib** [comment]
@ruinianxu indeed, this notebook is outdated. unfortunately, I do not have a GPU to try to fix it. will try to use Google colab for it

**Comment by alexlib** [comment]
This notebook is running 

https://colab.research.google.com/github/ericyang125/openpiv-python-gpu/blob/master/Openpiv_Python_Tutorial_Basic.ipynb

**Comment by ruinianxu** [comment]
Thanks for quick reply. I've figured out that cuda 10.1 works.
